#!/usr/bin/bash
# Generating all the models in a row
#npx sequelize-cli model:generate --name User --attributes email:string,password:string


npx sequelize-cli model:generate --name User --attributes email:string,password:string
npx sequelize-cli model:generate --name Service --attributes name:string
npx sequelize-cli model:generate --name Area --attributes name:string,serviceId:integer
npx sequelize-cli model:generate --name Manual --attributes name:string
npx sequelize-cli model:generate --name Guide --attributes name:string
npx sequelize-cli model:generate --name Owner --attributes name:string,image:string
npx sequelize-cli model:generate --name FinalDisposition --attributes description:string,finalDispositionDate:date,file:string
npx sequelize-cli model:generate --name RiskType --attributes name:string
npx sequelize-cli model:generate --name BiomedicalClassification --attributes name:string
npx sequelize-cli model:generate --name Technology --attributes name:string
npx sequelize-cli model:generate --name TicketStatus --attributes name:string
npx sequelize-cli model:generate --name Provider --attributes name:string
npx sequelize-cli model:generate --name DeviceType --attributes name:string
npx sequelize-cli model:generate --name AcquisitionType --attributes name:string
npx sequelize-cli model:generate --name Contract --attributes code:string,description:string,file:string,startDate:date

npx sequelize-cli model:generate --name DeviceStatus --attributes name:string
npx sequelize-cli model:generate --name Device --attributes name:string,image:string\
,code:string\
,oldCode:string\
,model:string\
,serial:string\
,cost:integer\
,location:string\
,acquisitionDate:date\
,installationDate:date\
,warehouseReceiptDate:date\
,manufacturingDate:date\
,status:integer\
,serviceId:integer\
,areaId:integer\
,manualId:integer\
,guideId:integer\
,ownerId:integer\
,finalDispositionId:integer\
,riskTypeId:integer\
,biomedicalClassificationId:integer\
,deviceStatusId:integer\
,deviceTypeId:integer\

npx sequelize-cli model:generate --name FileType --attributes name:string
npx sequelize-cli model:generate --name File --attributes name:string,fileTypeId:integer,deviceId:integer

npx sequelize-cli model:generate --name Plan --attributes scheduledDate:date,deviceId:integer,contractId:integer

npx sequelize-cli model:generate --name Acquisition --attributes code:string,file:string,providerId:integer,acquisitionDate:date,acquisitionTypeId:integer,externUrl:string

npx sequelize-cli model:generate --name Ticket --attributes name:string\
,reporterId:integer\
,title:string\
,description:string\
,ticketStatusId:integer\
,deviceId:integer\
,ticketFile:string\

npx sequelize-cli model:generate --name Calibration --attributes description:string,file:string,deviceId:integer,calibrationDate:date

npx sequelize-cli model:generate --name PreventiveMaintenance --attributes description:string,file:string,deviceId:integer,preventiveMaintenanceDate:date,providerId:integer

npx sequelize-cli model:generate --name CorrectiveMaintenance --attributes reportDate:date,deadLineDate:date,deviceId:integer,providerId:integer

npx sequelize-cli model:generate --name Note --attributes description:string,file:string,deviceId:integer,userId:integer,noteDate:date

npx sequelize-cli model:generate --name SparePartNeed --attributes name:string,status:boolean,preventiveMaintenanceId:integer,ticketId:integer,noteId:integer,correctiveMaintenanceId:integer

