#!/usr/bin/bash
# Generating all the models in a row
#npx sequelize-cli model:generate --name User --attributes email:string,password:string


npx sequelize-cli model:generate --name User --attributes email:string,password:string
npx sequelize-cli model:generate --name Service --attributes name:string
npx sequelize-cli model:generate --name Area --attributes name:string,serviceId:integer
npx sequelize-cli model:generate --name Manual --attributes name:string
npx sequelize-cli model:generate --name Guide --attributes name:string
npx sequelize-cli model:generate --name Owner --attributes name:string,image:string
npx sequelize-cli model:generate --name DeviceStatus --attributes name:string
npx sequelize-cli model:generate --name Device --attributes name:string,ServiceId:integer\
,code:string\
,model:string\
,serie:string\
,cost:integer\
,location:string\
,acquisitionDate:date\
,installationDate\
,status:integer\
,manualId:integer\
,guideId:integer\
,ownerId:integer\
,deviceStatusId:integer\
